#!/usr/bin/env python3
"""Compare formula-generated scalar quantizers and formula-reconstructed tensor blocks.

This is a research experiment, not a production checkpoint codec. It compares:
1. K-means codebook (reference baseline; one index per weight),
2. arithmetic-progression levels (uniform scalar quantization),
3. signed logarithmic companding levels (nonlinear formula; one index per weight),
4. blockwise linear polynomial reconstruction (no per-weight indices),
5. blockwise cubic polynomial reconstruction (no per-weight indices).

Every variant is serialized to an actual compressed NPZ, then decoded before metrics
are computed so the reported size/error reflect the stored representation.
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch
from safetensors import safe_open

import compress_tensor as base


def uniform_quantize(values: np.ndarray, levels: int) -> tuple[np.ndarray, dict[str, float]]:
    """Quantize with values generated by an arithmetic progression."""
    x = np.asarray(values, dtype=np.float32).reshape(-1)
    if levels < 2 or levels > 65536:
        raise ValueError("levels precisa estar entre 2 e 65536")
    lo = np.float32(np.min(x))
    hi = np.float32(np.max(x))
    step = np.float32((float(hi) - float(lo)) / (levels - 1)) if hi > lo else np.float32(0.0)
    dtype = np.uint8 if levels <= 256 else np.uint16
    if step == 0:
        q = np.zeros(x.size, dtype=dtype)
    else:
        q = np.rint((x - lo) / step).clip(0, levels - 1).astype(dtype)
    return q, {"minimum": float(lo), "step": float(step), "levels": int(levels)}


def uniform_reconstruct(indices: np.ndarray, params: dict[str, Any]) -> np.ndarray:
    q = np.asarray(indices, dtype=np.float32)
    return (np.float32(params["minimum"]) + q * np.float32(params["step"])).astype(np.float32)


def log_compand_quantize(values: np.ndarray, levels: int) -> tuple[np.ndarray, dict[str, float]]:
    """Signed log-companding: generate nonlinear levels from a few parameters."""
    x = np.asarray(values, dtype=np.float32).reshape(-1)
    if levels < 2 or levels > 65536:
        raise ValueError("levels precisa estar entre 2 e 65536")
    positive = np.abs(x)
    scale = float(np.median(positive))
    if not math.isfinite(scale) or scale <= np.finfo(np.float32).tiny:
        nonzero = positive[positive > 0]
        scale = float(np.median(nonzero)) if nonzero.size else 1.0
    scale32 = np.float32(max(scale, float(np.finfo(np.float32).tiny)))
    z = np.sign(x) * np.log1p(positive / scale32)
    zmax = np.float32(np.max(np.abs(z))) if z.size else np.float32(0.0)
    dtype = np.uint8 if levels <= 256 else np.uint16
    if zmax == 0:
        q = np.zeros(x.size, dtype=dtype)
    else:
        encoded = (z / zmax + 1.0) * (0.5 * (levels - 1))
        q = np.rint(encoded).clip(0, levels - 1).astype(dtype)
    return q, {"scale": float(scale32), "zmax": float(zmax), "levels": int(levels)}


def log_compand_reconstruct(indices: np.ndarray, params: dict[str, Any]) -> np.ndarray:
    q = np.asarray(indices, dtype=np.float32)
    levels = int(params["levels"])
    zmax = np.float32(params["zmax"])
    if zmax == 0:
        return np.zeros(q.size, dtype=np.float32)
    z = (q / (levels - 1) * 2.0 - 1.0) * zmax
    scale = np.float32(params["scale"])
    return (np.sign(z) * scale * np.expm1(np.abs(z))).astype(np.float32)


def polynomial_design(block_size: int, degree: int) -> np.ndarray:
    if block_size < degree + 2:
        raise ValueError("block_size precisa ser pelo menos degree + 2")
    t = np.linspace(-1.0, 1.0, block_size, dtype=np.float64)
    return np.polynomial.polynomial.polyvander(t, degree).astype(np.float32)


def fit_polynomial_blocks(
    values: np.ndarray,
    block_size: int,
    degree: int,
    coefficient_dtype: str = "fp16",
    chunk_blocks: int = 8192,
) -> tuple[np.ndarray, dict[str, Any]]:
    """Fit a small polynomial to each contiguous flattened block."""
    x = np.asarray(values, dtype=np.float32).reshape(-1)
    if x.size == 0:
        raise ValueError("tensor vazio")
    design = polynomial_design(block_size, degree)
    padding = (-x.size) % block_size
    padded = np.pad(x, (0, padding), mode="edge") if padding else x
    blocks = padded.reshape(-1, block_size)
    pinv = np.linalg.pinv(design.astype(np.float64)).astype(np.float32)
    target_dtype = np.float16 if coefficient_dtype == "fp16" else np.float32
    coeffs = np.empty((blocks.shape[0], degree + 1), dtype=target_dtype)
    for start in range(0, blocks.shape[0], chunk_blocks):
        end = min(blocks.shape[0], start + chunk_blocks)
        fitted = blocks[start:end] @ pinv.T
        coeffs[start:end] = fitted.astype(target_dtype)
    params = {
        "original_numel": int(x.size),
        "block_size": int(block_size),
        "degree": int(degree),
        "padding": int(padding),
        "coefficient_dtype": coefficient_dtype,
    }
    return coeffs, params


def reconstruct_polynomial_blocks(
    coeffs: np.ndarray,
    params: dict[str, Any],
    chunk_blocks: int = 8192,
) -> np.ndarray:
    degree = int(params["degree"])
    block_size = int(params["block_size"])
    design = polynomial_design(block_size, degree)
    stored = np.asarray(coeffs, dtype=np.float32)
    padded_size = stored.shape[0] * block_size
    padded = np.empty(padded_size, dtype=np.float32)
    for start in range(0, stored.shape[0], chunk_blocks):
        end = min(stored.shape[0], start + chunk_blocks)
        rebuilt = stored[start:end] @ design.T
        padded[start * block_size : end * block_size] = rebuilt.reshape(-1)
    return padded[: int(params["original_numel"])]


def weight_metrics(original: np.ndarray, reconstructed: np.ndarray) -> dict[str, float]:
    x = np.asarray(original, dtype=np.float32).reshape(-1)
    y = np.asarray(reconstructed, dtype=np.float32).reshape(-1)
    diff = x.astype(np.float64) - y.astype(np.float64)
    mse = float(np.mean(diff * diff))
    x64, y64 = x.astype(np.float64), y.astype(np.float64)
    xn = float(np.linalg.norm(x64))
    yn = float(np.linalg.norm(y64))
    cosine = float(np.dot(x64, y64) / (xn * yn)) if xn and yn else (1.0 if not xn and not yn else 0.0)
    std = float(np.std(x64))
    return {
        "rmse": math.sqrt(max(0.0, mse)),
        "mae": float(np.mean(np.abs(diff))),
        "max_abs_error": float(np.max(np.abs(diff))) if diff.size else 0.0,
        "weight_std": std,
        "rmse_over_weight_std": math.sqrt(max(0.0, mse)) / std if std else 0.0,
        "cosine_similarity_flat_weights": cosine,
    }


def projection_probe(original: np.ndarray, reconstructed: np.ndarray, shape: tuple[int, ...], batch: int, seed: int) -> dict[str, Any] | None:
    if len(shape) != 2 or batch <= 0:
        return None
    rows, cols = shape
    w = np.asarray(original, dtype=np.float32).reshape(rows, cols)
    wr = np.asarray(reconstructed, dtype=np.float32).reshape(rows, cols)
    rng = np.random.default_rng(seed)
    inputs = rng.standard_normal((cols, batch), dtype=np.float32)
    inputs /= math.sqrt(max(1, cols))
    y = w @ inputs
    yr = wr @ inputs
    yd, yrd = y.astype(np.float64), yr.astype(np.float64)
    difference = yd - yrd
    rms = float(np.sqrt(np.mean(yd * yd)))
    ny, nyr = float(np.linalg.norm(yd)), float(np.linalg.norm(yrd))
    cosine = float(np.sum(yd * yrd) / (ny * nyr)) if ny and nyr else 0.0
    return {
        "batch_size": int(batch),
        "output_rmse": float(np.sqrt(np.mean(difference * difference))),
        "output_rmse_over_original_rms": float(np.sqrt(np.mean(difference * difference)) / rms) if rms else 0.0,
        "output_cosine_similarity": cosine,
        "note": "Entradas gaussianas sintéticas; não substitui logits, ativações reais ou perplexidade.",
    }


def write_artifact(path: Path, arrays: dict[str, np.ndarray], metadata: dict[str, Any]) -> int:
    meta_bytes = json.dumps(metadata, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    arrays["metadata"] = np.frombuffer(meta_bytes, dtype=np.uint8)
    np.savez_compressed(path, **arrays)
    return path.stat().st_size


def sample_weights(x: np.ndarray, sample_size: int, seed: int) -> np.ndarray:
    if x.size <= sample_size:
        return x
    rng = np.random.default_rng(seed)
    chosen = rng.choice(x.size, size=sample_size, replace=False)
    return x[chosen]


def run_experiment(
    name: str,
    x: np.ndarray,
    shape: tuple[int, ...],
    source_bytes: int,
    outdir: Path,
    params: dict[str, Any],
    arrays: dict[str, np.ndarray],
    reconstructed: np.ndarray,
    batch: int,
    seed: int,
) -> dict[str, Any]:
    safe_name = re.sub(r"[^A-Za-z0-9_.-]+", "_", name)
    artifact_path = outdir / f"{safe_name}.npz"
    meta = {
        "method": name,
        "shape": list(shape),
        "numel": int(x.size),
        "source_tensor_bytes": int(source_bytes),
        "formula_parameters": params,
        "reconstruction": "decoded from formula and stored parameter arrays",
    }
    size = write_artifact(artifact_path, arrays, meta)
    # Metrics are computed on the exact values reconstructed from stored parameters.
    metrics = weight_metrics(x, reconstructed)
    projection = projection_probe(x, reconstructed, shape, batch, seed)
    result = {
        "method": name,
        "artifact_path": str(artifact_path.resolve()),
        "artifact_npz_bytes_actual": int(size),
        "artifact_npz_MB_actual": size / 1_000_000,
        "source_tensor_bytes": int(source_bytes),
        "source_tensor_MB": source_bytes / 1_000_000,
        "saved_MB": (source_bytes - size) / 1_000_000,
        "savings_pct_vs_source_tensor": (1.0 - size / source_bytes) * 100.0 if source_bytes else 0.0,
        "full_tensor_weight_reconstruction_error": metrics,
        "linear_projection_probe": projection,
        "formula_parameters": params,
    }
    (outdir / f"{safe_name}_report.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=base.DEFAULT_MODEL, help="Repo HF, pasta local ou arquivo Safetensors")
    parser.add_argument("--revision", default=None)
    parser.add_argument("--cache-dir", default=None)
    parser.add_argument("--tensor-name", default=None, help="Nome exato do tensor; se omitido, escolhe uma matriz 2D intermediária")
    parser.add_argument("--max-auto-elements", type=int, default=20_000_000)
    parser.add_argument("--list-tensors", action="store_true")
    parser.add_argument("--levels", type=int, default=256, help="Níveis das duas fórmulas escalares (padrão: 256)")
    parser.add_argument("--sample-size", type=int, default=250_000, help="Amostra para treinar o K-means de referência")
    parser.add_argument("--block-size", type=int, default=256, help="Pesos contíguos representados por cada polinômio")
    parser.add_argument("--coefficient-dtype", choices=["fp16", "fp32"], default="fp16")
    parser.add_argument("--projection-batch", type=int, default=4, help="Colunas de X no teste W@X; 0 desativa")
    parser.add_argument("--output-dir", default="formula_tensor_test")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.levels < 2 or args.levels > 256:
        parser.error("--levels deve estar entre 2 e 256 nesta primeira versão")
    if args.block_size < 5:
        parser.error("--block-size precisa ser pelo menos 5 para o polinômio cúbico")

    started = time.time()
    files = base.resolve_model(args.model, args.cache_dir, args.revision)
    if args.list_tensors:
        for item in base.list_tensors(files)[:100]:
            print(f"{item['name']}\tshape={item['shape']}\tnumel={item['numel']}\tfile={item['file'].name}")
        return 0
    chosen = base.choose_tensor(files, args.tensor_name, args.max_auto_elements)
    print(f"[tensor] {chosen['name']} shape={chosen['shape']} numel={chosen['numel']}")
    with safe_open(str(chosen["file"]), framework="pt", device="cpu") as sf:
        tensor = sf.get_tensor(chosen["name"])
    original_shape = tuple(int(v) for v in tensor.shape)
    source_dtype = str(tensor.dtype).replace("torch.", "")
    source_bytes = int(tensor.numel() * tensor.element_size())
    x = tensor.float().cpu().numpy().reshape(-1).copy()
    if not np.isfinite(x).all():
        raise ValueError("O tensor selecionado contém NaN ou infinito; experimento interrompido.")
    del tensor

    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", chosen["name"])
    sample = sample_weights(x, args.sample_size, args.seed)
    results: list[dict[str, Any]] = []

    # Reference: learned K-means representatives and one symbol/index per weight.
    centers = np.sort(base.weighted_kmeans_1d(sample, args.levels))
    indices = base.assign_indices(x, centers, chunk_size=2_000_000)
    k_recon = centers[indices.astype(np.int64)]
    k_result = run_experiment(
        "baseline_kmeans", x, original_shape, source_bytes, outdir,
        {"levels_requested": args.levels, "actual_centers": int(centers.size), "index_per_weight": True},
        {"centers_fp32": centers.astype(np.float32), "indices": indices},
        k_recon, args.projection_batch, args.seed,
    )
    results.append(k_result)

    # Formula 1: arithmetic progression, no stored codebook.
    q_linear, p_linear = uniform_quantize(x, args.levels)
    linear_recon = uniform_reconstruct(q_linear, p_linear)
    p_linear = {**p_linear, "formula": "value_i = minimum + index_i * step", "index_per_weight": True}
    results.append(run_experiment(
        "formula_arithmetic_levels", x, original_shape, source_bytes, outdir, p_linear,
        {"indices": q_linear, "parameters_fp32": np.array([p_linear["minimum"], p_linear["step"]], dtype=np.float32)},
        linear_recon, args.projection_batch, args.seed,
    ))

    # Formula 2: nonlinear signed logarithmic companding, also with no stored codebook.
    q_log, p_log = log_compand_quantize(x, args.levels)
    log_recon = log_compand_reconstruct(q_log, p_log)
    p_log = {**p_log, "formula": "z=sign(w)*log(1+abs(w)/scale); w'=sign(z')*scale*(exp(abs(z'))-1)", "index_per_weight": True}
    results.append(run_experiment(
        "formula_log_companding", x, original_shape, source_bytes, outdir, p_log,
        {"indices": q_log, "parameters_fp32": np.array([p_log["scale"], p_log["zmax"]], dtype=np.float32)},
        log_recon, args.projection_batch, args.seed,
    ))

    # Formula 3: two coefficients per block.
    for degree, name in ((1, "formula_block_linear"), (3, "formula_block_cubic")):
        coeffs, p_poly = fit_polynomial_blocks(x, args.block_size, degree, args.coefficient_dtype)
        poly_recon = reconstruct_polynomial_blocks(coeffs, p_poly)
        params = {
            **p_poly,
            "formula": "w_i = a0 + a1*t + ... + a_degree*t^degree; t in [-1,1] per block",
            "index_per_weight": False,
            "coefficient_count": int(coeffs.size),
            "parameter_bytes_before_archive_compression": int(coeffs.nbytes),
        }
        results.append(run_experiment(
            name, x, original_shape, source_bytes, outdir, params,
            {"block_coefficients": coeffs},
            poly_recon, args.projection_batch, args.seed,
        ))

    summary = {
        "status": "formula_experiments_completed",
        "model_or_path": args.model,
        "tensor_name": chosen["name"],
        "shape": list(original_shape),
        "source_dtype": source_dtype,
        "numel": int(x.size),
        "source_tensor_bytes": source_bytes,
        "source_tensor_MB": source_bytes / 1_000_000,
        "levels": args.levels,
        "block_size": args.block_size,
        "coefficient_dtype": args.coefficient_dtype,
        "results": results,
        "limitations": [
            "Somente um tensor é medido; os arquivos não constituem um checkpoint Transformers completo.",
            "As fórmulas escalares ainda guardam um índice por peso; sua vantagem é não guardar um codebook explícito.",
            "Os métodos polinomiais guardam coeficientes por bloco e nenhum índice individual, mas pesos em ordem linear podem não ter suavidade local.",
            "A redução é calculada sobre o tamanho do tensor-fonte no dtype original versus o NPZ realmente escrito; inclui os metadados do artefato.",
            "W@X usa entradas gaussianas sintéticas, não ativações reais; erro baixo não garante a qualidade linguística do modelo.",
            "Os cinco arquivos usam a mesma estratégia NPZ/Deflate, permitindo comparação interna direta entre métodos.",
        ],
        "elapsed_seconds": round(time.time() - started, 2),
    }
    summary_path = outdir / f"{stem}_formula_comparison.json"
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print("\n=== COMPARAÇÃO DE FÓRMULAS ===")
    print(f"Tensor: {chosen['name']} | shape={original_shape} | dtype={source_dtype}")
    print(f"Original: {source_bytes / 1e6:.3f} MB | níveis={args.levels} | bloco={args.block_size} | coeficientes={args.coefficient_dtype}")
    print(f"{'MÉTODO':29s} {'ARQUIVO MB':>11s} {'REDUÇÃO':>9s} {'RMSE/std':>10s} {'COS PESOS':>10s} {'ERRO W@X':>10s}")
    for item in results:
        m = item["full_tensor_weight_reconstruction_error"]
        probe = item["linear_projection_probe"]
        werr = probe["output_rmse_over_original_rms"] if probe else float("nan")
        print(f"{item['method']:29s} {item['artifact_npz_MB_actual']:11.3f} {item['savings_pct_vs_source_tensor']:8.2f}% {m['rmse_over_weight_std']:10.5f} {m['cosine_similarity_flat_weights']:10.6f} {werr:10.5f}")
    print(f"\nRelatório consolidado: {summary_path.resolve()}")
    print("Observação: arquivos menores que a entrada não implicam automaticamente inferência mais rápida.")
    print(f"Tempo total: {time.time() - started:.2f}s")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrompido pelo usuário.", file=sys.stderr)
        raise SystemExit(130)
