#!/usr/bin/env python3
"""Fit a compact 2-D Fourier formula to every weight of one real checkpoint tensor.

The script exports every source weight to a float32 NPY file, then fits several
truncated Fourier representations of the entire matrix. Each saved formula keeps
only a small set of frequency coefficients; the omitted values are generated by
the inverse Fourier formula instead of stored individually.

This is an experiment. Weight-space reconstruction error does not prove language
quality is preserved.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch
from safetensors import safe_open

import compress_tensor as base


def parse_positive_ints(value: str) -> list[int]:
    try:
        values = sorted({int(part.strip()) for part in value.split(",") if part.strip()})
    except ValueError as error:
        raise argparse.ArgumentTypeError("Use inteiros positivos separados por vírgulas.") from error
    if not values or any(value < 1 for value in values):
        raise argparse.ArgumentTypeError("Use inteiros positivos separados por vírgulas.")
    return values


def frequency_rows(rows: int, cutoff: int) -> np.ndarray:
    """Return positive and negative row frequencies inside a symmetric low-pass band."""
    safe_cutoff = min(cutoff, max(0, (rows - 1) // 2))
    indices = np.arange(rows, dtype=np.int64)
    distance = np.minimum(indices, rows - indices)
    return np.flatnonzero(distance <= safe_cutoff).astype(np.int32)


def fit_fourier_formula(weights: np.ndarray, cutoff: int) -> dict[str, np.ndarray | int]:
    """Fit a 2-D low-frequency Fourier formula using the complete source matrix."""
    matrix = np.asarray(weights, dtype=np.float32)
    if matrix.ndim != 2:
        raise ValueError(f"A fórmula exige uma matriz 2D; forma recebida: {matrix.shape}")
    rows, cols = matrix.shape
    row_indices = frequency_rows(rows, cutoff)
    col_cutoff = min(cutoff, cols // 2)

    spectrum = np.fft.rfft2(matrix)
    selected = spectrum[np.ix_(row_indices, np.arange(col_cutoff + 1))]

    # Store each complex coefficient as two FP16 values to measure a compact,
    # portable representation rather than preserving a full complex128 FFT.
    return {
        "real": selected.real.astype(np.float16),
        "imag": selected.imag.astype(np.float16),
        "row_indices": row_indices,
        "shape": np.asarray([rows, cols], dtype=np.int64),
        "col_cutoff": int(col_cutoff),
        "cutoff": int(cutoff),
    }


def save_formula(path: Path, formula: dict[str, np.ndarray | int], tensor_name: str) -> int:
    metadata = {
        "format": "RC-IA 2D Fourier formula",
        "version": 1,
        "tensor_name": tensor_name,
        "max_frequency": int(formula["cutoff"]),
        "shape": np.asarray(formula["shape"]).astype(int).tolist(),
        "coefficient_dtype": "float16 real + float16 imaginary",
        "formula": "W_hat[r,c] = inverse_rfft2(C)[r,c], using only stored low-frequency Fourier coefficients",
    }
    np.savez_compressed(
        path,
        real=formula["real"],
        imag=formula["imag"],
        row_indices=formula["row_indices"],
        shape=formula["shape"],
        col_cutoff=np.asarray([formula["col_cutoff"]], dtype=np.int32),
        metadata_json=np.asarray(json.dumps(metadata, ensure_ascii=False)),
    )
    return path.stat().st_size


def reconstruct_formula(path: Path) -> tuple[np.ndarray, dict[str, Any]]:
    """Recreate the whole matrix exclusively from a saved compact formula."""
    with np.load(path, allow_pickle=False) as archive:
        rows, cols = (int(x) for x in archive["shape"])
        row_indices = archive["row_indices"].astype(np.int64)
        real = archive["real"].astype(np.float32)
        imag = archive["imag"].astype(np.float32)
        col_cutoff = int(archive["col_cutoff"][0])
        metadata = json.loads(str(archive["metadata_json"].item()))

    spectrum = np.zeros((rows, cols // 2 + 1), dtype=np.complex64)
    spectrum[np.ix_(row_indices, np.arange(col_cutoff + 1))] = real + 1j * imag
    reconstructed = np.fft.irfft2(spectrum, s=(rows, cols)).astype(np.float32)
    return reconstructed, metadata


def calculate_metrics(original: np.ndarray, reconstructed: np.ndarray) -> dict[str, float]:
    x = np.asarray(original, dtype=np.float64)
    y = np.asarray(reconstructed, dtype=np.float64)
    difference = y - x
    rmse = float(np.sqrt(np.mean(difference * difference)))
    std = float(np.std(x))
    norm_x = float(np.linalg.norm(x))
    norm_y = float(np.linalg.norm(y))
    cosine = float(np.sum(x * y) / (norm_x * norm_y)) if norm_x and norm_y else 0.0
    return {
        "rmse": rmse,
        "rmse_over_original_std": rmse / std if std else 0.0,
        "relative_l2_error": float(np.linalg.norm(difference) / norm_x) if norm_x else 0.0,
        "cosine_similarity": cosine,
        "max_absolute_error": float(np.max(np.abs(difference))) if difference.size else 0.0,
        "original_std": std,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=base.DEFAULT_MODEL, help="Diretório local, arquivo Safetensors ou ID do Hugging Face")
    parser.add_argument("--revision", default=None)
    parser.add_argument("--cache-dir", default=None)
    parser.add_argument("--tensor-name", default=None, help="Nome exato do tensor 2D; sem isso escolhe uma matriz automaticamente")
    parser.add_argument("--max-auto-elements", type=int, default=20_000_000)
    parser.add_argument("--list-tensors", action="store_true")
    parser.add_argument("--frequencies", type=parse_positive_ints, default=parse_positive_ints("8,16,32,64,128,256"),
                        help="Cortes de frequência para as fórmulas, separados por vírgula (padrão: 8,16,32,64,128,256)")
    parser.add_argument("--output-dir", default="formula_fit_layer_results")
    args = parser.parse_args()

    started = time.perf_counter()
    files = base.resolve_model(args.model, args.cache_dir, args.revision)
    if args.list_tensors:
        candidates = base.list_tensors(files)
        for item in candidates:
            print(f"{item['name']}\tshape={item['shape']}\tparams={item['numel']:,}\t{item['file'].name}")
        return 0

    selected = base.choose_tensor(files, args.tensor_name, args.max_auto_elements)
    if len(selected["shape"]) != 2:
        print(f"[ERRO] O tensor selecionado não é uma matriz 2D: {selected['name']} {selected['shape']}", file=sys.stderr)
        return 2

    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"Tensor: {selected['name']}", flush=True)
    print(f"Arquivo: {selected['file']}", flush=True)
    print(f"Dimensões: {selected['shape']} | pesos: {selected['numel']:,}", flush=True)

    with safe_open(str(selected["file"]), framework="pt", device="cpu") as source:
        source_tensor = source.get_tensor(selected["name"])
        source_dtype = str(source_tensor.dtype).replace("torch.", "")
        source_tensor_bytes = int(source_tensor.numel() * source_tensor.element_size())
        original = source_tensor.to(dtype=torch.float32).cpu().numpy().copy()
        del source_tensor

    original_path = output_dir / "weights_original.npy"
    np.save(original_path, original, allow_pickle=False)
    print(f"Todos os pesos exportados: {original_path} ({original_path.stat().st_size:,} bytes em FP32)", flush=True)

    report: dict[str, Any] = {
        "tensor_name": selected["name"],
        "source_file": str(selected["file"]),
        "shape": list(original.shape),
        "num_weights": int(original.size),
        "source_dtype": source_dtype,
        "original_tensor_bytes": source_tensor_bytes,
        "original_export_path": str(original_path),
        "original_export_bytes": original_path.stat().st_size,
        "formula": "2-D low-frequency Fourier series",
        "variants": [],
    }

    for cutoff in args.frequencies:
        print(f"\nAjustando fórmula com frequência máxima {cutoff}...", flush=True)
        formula = fit_fourier_formula(original, cutoff)
        artifact = output_dir / f"fourier_formula_f{cutoff:04d}.npz"
        artifact_bytes = save_formula(artifact, formula, selected["name"])
        reconstructed, metadata = reconstruct_formula(artifact)
        metrics = calculate_metrics(original, reconstructed)
        coefficient_count = int(np.asarray(formula["real"]).size)
        result = {
            "max_frequency": cutoff,
            "coefficient_count": coefficient_count,
            "coefficient_bytes_uncompressed": coefficient_count * 4,
            "artifact_path": str(artifact),
            "artifact_bytes": artifact_bytes,
            "effective_bits_per_weight": artifact_bytes * 8 / original.size,
            "compression_vs_source_tensor_percent": 100.0 * (1.0 - artifact_bytes / source_tensor_bytes)
                if source_tensor_bytes else 0.0,
            **metrics,
        }
        report["variants"].append(result)
        print(
            f"coeficientes={coefficient_count:,} | arquivo={artifact_bytes:,} bytes | "
            f"{result['effective_bits_per_weight']:.4f} bits/peso | "
            f"RMSE/std={metrics['rmse_over_original_std']:.6f} | "
            f"cos={metrics['cosine_similarity']:.6f}",
            flush=True,
        )
        del formula, reconstructed

    report_path = output_dir / "formula_fit_report.json"
    report["elapsed_seconds"] = time.perf_counter() - started
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\nRelatório: {report_path}")
    print(f"Tempo total: {report['elapsed_seconds']:.1f}s")
    print("Nota: métricas dos pesos não demonstram, sozinhas, a qualidade de geração do modelo.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
